version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_SHEETS_IDS=${GOOGLE_SHEETS_IDS}
      - WB_API_TOKEN=${WB_API_TOKEN}
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
